spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID:default_id}
              client-secret: ${GOOGLE_CLIENT_SECRET:default_secret}
              scope:
                - openid
                - profile
                - email
      user:
        name: admin
        password: password
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    #loggin of sql query

  sql:
    init:
      mode: always
server:
  port: 8081
jwt:
  secret: ${JWT_SECRET:defaultSeceret}
gemini:
  api:
    key: ${GEMINI_API_KEY:122131EDFAS}